version: '3'
services:
  jupyter:
    user: $UID
    build: .
    image: kotaroito/jupyter
    environment:
      - HOME=/tmp
    working_dir: /tmp
    ports:
     - "$PORT:$PORT"
    volumes:
     - ./notebooks:/tmp/notebooks
    command: >-
      jupyter notebook --ip=0.0.0.0 --port $PORT
