version: '3'
services:
  base: &base
    user: $UID
    build: .
    image: notebook:latest
    working_dir: /tmp
    environment:
      - HOME=/tmp
    ports:
      - "$PORT:$PORT"
  notebook:
    <<: *base
    working_dir: /tmp
    volumes:
     - ./notebooks:/tmp/notebooks
     - ./data:/tmp/data
    command: >-
      jupyter notebook --ip=0.0.0.0 --port $PORT
  example:
    <<: *base
    volumes:
     - ./examples:/tmp/examples
     - ./data:/tmp/data     
